#!/bin/sh

cd "$(dirname "$0")"/css
rm houseplanner.css
for f in $(find ./src/ -name '*.css')
do
	#cat "$f" >> "css/houseplanner.css"
	java -jar yuicompressor.jar --type css "$f" >> ../css/houseplanner.css
done

cd "$(dirname "$0")"/js/
rm houseplanner.js
rm three/three.extras.js
java -jar compiler.jar --language_in ECMASCRIPT5 --js src/library/jquery.js --js `find src/* -type f ! -name *jquery.js ! -name *.DS_Store` --js_output_file houseplanner.js
java -jar compiler.jar --language_in ECMASCRIPT5 --js_output_file three/three.extras.js 'three/extras/**.js'
