#!/bin/sh

cd "$(dirname "$0")"

if [ ! -f /usr/local/bin/brew ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ ! -d /usr/local/Cellar/node/ ]; then
    brew install node
    npm install argparse
    npm install uglify-js
    npm install node-minify
fi

cd js/three/build/
node ./build.js --include common --include extras --minify --output ../three.js
rm ../three.js.map

#cd ../../two/build/
#node ./build.js --minify
#rm ../two.js
#rm ../two.clean.js
#mv ../two.min.js ../two.js

cd ../../../
for f in $(find ./css/src/ -name '*.css')
do
	#cat "$f" >> "css/houseplanner.css"
	java -jar ./css/yuicompressor.jar --type css "$f" >> ./js/houseplanner.css
done

java -jar ./js/compiler.jar --language_in ECMASCRIPT5 --js_output_file=js/library.js 'js/library/**.js'
java -jar ./js/compiler.jar --language_in ECMASCRIPT5 --js_output_file=js/three/three-extra.js 'js/three/extras/**.js'
java -jar ./js/compiler.jar  --language_in ECMASCRIPT5 --js_output_file=js/src.js 'js/src/**.js' 

cd js/
rm houseplanner.js
#cat two/two.js >> houseplanner.js
cat fabric/fabric.js >> houseplanner.js
cat src.js >> houseplanner.js
#cat three/three.js >> houseplanner.js
cat three/three-extra.js >> houseplanner.js
cat library.js >> houseplanner.js
zip houseplanner.jsz houseplanner.js houseplanner.css three/three.js
rm houseplanner.js
rm houseplanner.css
rm library.js
rm three/three-extra.js
rm src.js

#cd "$(dirname "$0")"
#java -jar ./js/compiler.jar  --language_in ECMASCRIPT6 --compilation_level ADVANCED_OPTIMIZATIONS --js_output_file=js/h.js 'js/houseplanner.js' 


