#!/bin/sh

cd "$(dirname "$0")"

if [ ! -f /usr/local/bin/brew ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ ! -d /usr/local/Cellar/node/ ]; then
    brew install node
    npm install argparse

    npm install -g bower
    npm install uglify-js
    npm install prepro
    npm install acorn
    npm install straps
    npm install stats.js
    ./js/paper/build/minify-components.sh
fi

cd js/three/build/
rm -rf ../src/audio
node ./build.js --include common --include extras --minify --output ../three.js
rm ../three.js.map

cd ../../paper/build/
rm -rf jsdoc-toolkit
#./build.sh
#./minify.sh
#rm ../paper.js
rm ../dist/paper-core.js
rm ../dist/paper-full.js
rm ../dist/paper-node.js
rm ../dist/paper-core.min.js
mv ../dist/paper-full.min.js ../paper.js

cd ../../../css/
rm houseplanner.css
for f in $(find ./src/ -name '*.css')
do
	#cat "$f" >> "css/houseplanner.css"
	java -jar yuicompressor.jar --type css "$f" >> ../css/houseplanner.css
done

cd ../js/

java -jar compiler.jar  --language_in ECMASCRIPT5 --js_output_file=src.js 'src/**.js'
java -jar compiler.jar --language_in ECMASCRIPT5 --js_output_file=library.js 'library/**.js'
java -jar compiler.jar --language_in ECMASCRIPT5 --js_output_file=three/three-extra.js 'three/extras/**.js'

rm houseplanner.jsz
cat src.js >> houseplanner.js
cat three/three-extra.js >> houseplanner.js
cat library.js >> houseplanner.js
zip houseplanner.jsz houseplanner.js three/three.js paper/paper.js
rm houseplanner.js
rm library.js
rm three/three-extra.js
rm src.js

#cd "$(dirname "$0")"
#java -jar ./js/compiler.jar  --language_in ECMASCRIPT6 --compilation_level ADVANCED_OPTIMIZATIONS --js_output_file=js/h.js 'js/houseplanner.js' 


