#!/bin/sh

find "$(dirname "$0")" -name '*.blend1' | while read f; do
    cd "$(dirname "$f")"
	rm "$f"
done

find "$(dirname "$0")" -name '*.DS_Store' | while read f; do
    cd "$(dirname "$f")"
	rm "$f"
done

find "$(dirname "$0")" -name "*.json" | while read f; do
    cd "$(dirname "$f")"
    if [ -f "$(basename "$f" .json).blend" ]; then
	   rm "$f"
    fi
done

find "$(dirname "$0")/../scenes/" -name '*.blend1' | while read f; do
    cd "$(dirname "$f")"
    rm "$f"
done

find "$(dirname "$0")/../scenes/" -name "*.json" | while read f; do
    cd "$(dirname "$f")"
    if [ -f "$(basename "$f" .json).blend" ]; then
       rm "$f"
    fi
done