#!/bin/sh

cd "$(dirname "$0")"

#for f in $(find ./ -name '*.blend')
find './' -name '*.blend' | while read f
do
	cd "$(dirname "$0")/$(dirname "$f")"

	open -n /Applications/blender.app "$(basename "$f")"
	#/Applications/blender.app/Contents/MacOS/blender -b "$(basename "$f")"

	#sleep 2
	#osascript -e 'tell application "Blender" to activate'
	sleep 4

	cliclick -w 650 -r c:300,30 c:60,60 c:80,440 c:340,600 c:1600,105
	#cliclick -w 640 -r c:300,30 c:60,60 c:60,440 c:340,700 c:1600,105

	while [ ! -f "$(basename "$f" .blend).json" ]
	do
	    sleep 1
	done
	sleep 1
	pkill -9 "blender"
	sleep 1
	#osascript -e 'repeat\nif application "Blender" is not running then exit repeat\ndelay 5\nend repeat'
done