#!/bin/sh

cd "$(dirname "$0")/../"

rm "./php/update.sql"

i=0
CATEGORY=0

#for d in `echo $(find ./objects -type d)`
find "./objects" -type d  | while read d
do
    #echo "$d"

   if [[ "$d" != *"/Textures"* ]]
   then

   		NAME[$i]="$d"
		c=0
		for a in "${NAME[@]}"
    	do
    		if [[ $(dirname "$d") == "$a" ]]
    		then
        		CATEGORY=$c
        		break
        	fi
        	c=$(($c + 1))
    	done

    	echo "${NAME[$i]}($i) -> $CATEGORY"

    	if (( $CATEGORY == 0))
    	then
    		echo "INSERT INTO CATEGORIES (ID, SUB_ID, NAME) VALUES ($i, 0, '$(basename "$d")');" >> "./php/update.sql"
    	else
    		echo "INSERT INTO CATEGORIES (ID, SUB_ID, NAME) VALUES ($i, $CATEGORY, '$(basename "$d")');" >> "./php/update.sql"
    	  
            find "$d" -name '*.jsz' | while read f
            do
                if [[ $(dirname "$f") == "$d" ]]
                then
                    echo "INSERT INTO OBJECTS (NAME, IMAGE, FILE, CATEGORY_ID) VALUES ('$(basename "$f" .jsz)', '$(dirname "$f")/$(basename "$f" .jsz).jpg', '$f', $i);" >> "./php/update.sql"
                fi
            done
        fi

    	i=$(($i + 1))
	fi
done
