#!/bin/sh

ROOT="$(dirname "$0")"
cd "$ROOT"


#for f in $(find ./ -name '*.js')
find "$ROOT" -name '*.json' | while read f
do
    if [ "$(basename "$f")" != "index.json" ]
    then
      DIR="$(dirname "$f")"
	    cd "$DIR"
       #Fix Texture Path
       #============================
       #cat "$(basename "$f")" | sed -e "s/\"mapDiffuse\": \"/\"mapDiffuse\": \"Textures\\/g" > "$(basename "$f").txt"

      #Compress JSON (json limit fix)
      #============================
      #java -jar "$ROOT/../css/yuicompressor.jar" -o "$DIR/$(basename "$f").js" "$DIR/$(basename "$f")"
      #mv "$(basename "$f").js" "$(basename "$f")"

       #Zip 3D Model
       #============================
	     #zip "${f%.*}.jsz" "${f%.*}.js"
       rm "$(basename "$f" .json).jsz"
	     zip "$(basename "$f" .json).jsz" "$(basename "$f")"
	     #tar -czf "${f%.*}.jsz" "$f"
    fi
done

#Encrypt 3D Models
#============================
#for f in $(find ./ -name '*.jsz')
#do
	#openssl base64 -in "$f" -out "$f.base64"
	#base64  -i "$f" -o "$f.base64"
#done
