#!/bin/sh

find "$(dirname "$0")" -name "*.json" | while read f; do
	cd "$(dirname "$f")"
  if [ -f "$(basename "$f" .json).blend" ]; then
    #Fix Texture Path
    #============================
    #cat "$(basename "$f")" | sed -e "s/\"mapDiffuse\":\"/\"mapDiffuse\":\"Textures\\/g" > "$(basename "$f").txt"
    rm "$(basename "$f" .json).jsz"
    zip "$(basename "$f" .json).jsz" "$(basename "$f")"
  fi
done

find "$(dirname "$0")/../scenes/" -name "*.json" | while read f ; do
  cd "$(dirname "$f")"
  if [ -f "$(basename "$f" .json).blend" ]; then
    rm "$(basename "$f" .json).jsz"
    zip "$(basename "$f" .json).jsz" "$(basename "$f")"
  fi
done